linters:
  disbale-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gci
    - goconst
    - gocritic
    - gofmt
    - gomnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace

linters-settings:
  goconst:
    min-len: 2
    min-occurences: 3
  gocritic:
    enable-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gomnd:
    ignored-functions:
      - "make"
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true
